### ISSUE TITLE
No live streaming

### ISSUE THREAD

**Issue by dannielum** [nonsleepr/ha-eufy-security#10]
I am able to get the camera to show the last still recorded picture but not streaming it live. Here is the error I see in the log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 491, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 508, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/eufy_security/camera.py", line 100, in async_camera_image
    if self._last_image_url != self._camera.last_camera_image_url:
  File "/usr/local/lib/python3.7/site-packages/eufy_security/camera.py", line 30, in last_camera_image_url
    return self.camera_info["cover_path"]
KeyError: 'cover_path'
```

Any help is appreciated. Thanks!

**Comment by R0GGER** [comment]
Try to disable "Preload Stream" in all streams...

**Comment by dannielum** [comment]
> Try to disable "Preload Stream" in all streams...

That didn't work either. However, I notice that if I call the `camera.turn_on` service on the eufy camera entity, it will live stream in the Lovestream UI. Not sure if that is the right approach because it will cause eufy security to stop recording when I do that and probably will exhaust the battery too.

**Comment by PrayerfulDrop** [comment]
I have the same issue as @dannielum.  Only see the still photo.

**Comment by marklester** [comment]
same here 
```
[homeassistant.components.camera] Error requesting stream: camera.doorbell does not support play stream service
```

**Comment by t3miLo** [comment]
I was running release tag : `v0.3.0` and i was getting the same issue, but i changed to the `master` branch and im now able to have my camera and doorbell stream. the only thing it looks theres http request every few seconds for the thumbnail/still photo when on the lovelace card 
![image](https://user-images.githubusercontent.com/34803692/90444478-6f648e80-e0cd-11ea-9848-9fd6c9bc9f58.png)

**Comment by xekil** [comment]
same problem ; (

**Comment by rafaelmagalhaes** [comment]
any updates on this, I'm unable to play live streams on my cameras and doorbell

I have tried calling camera.turnon service but doesn't work,

I did a manual installation, from master branch

2020-09-08 07:59:22 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.doorbell does not support play stream service

**Comment by a-bianucci** [comment]
I have the same issue on v3

**Comment by csrui** [comment]
I have just installed v0.3.0, all 4 cameras entities are shown as picture but no streaming support also.

> Logger: homeassistant.components.camera
> Source: components/camera/__init__.py:609
> Integration: Camera (documentation, issues)
> First occurred: 12:43:30 AM (13 occurrences)
> Last logged: 12:50:59 AM
> 
>     Error requesting stream: camera.doorbell does not support play stream service
>     Error requesting stream: camera.bedroom does not support play stream service

Home Assistant

> version: 0.118.0
> installation_type: Home Assistant Container
> dev: false
> hassio: false
> docker: true
> virtualenv: false
> python_version: 3.8.6
> os_name: Linux
> os_version: 5.4.0-53-generic
> arch: x86_64
> timezone: Europe/Lisbon

If I can provide any extra feedback just let me know.

**Comment by conorlap** [comment]
Same issues as above - any idea if this can be fixed?

Error requesting stream: camera.doorbell does not support play stream service
Error requesting stream: camera.bedroom does not support play stream service

**Comment by htuomola** [comment]
I tried digging around a bit (I'm new to HA "internals") and my guess is that this integration doesn't declare camera.play_stream service. Probably declaring that service is easier but implementing it (getting camera stream) is the bigger part. Though it seems it might've been implemented e.g. in [ioBroker library](https://github.com/bropat/ioBroker.eufy-security/blob/master/src/lib/eufy-security/eufy-security.ts#L121)
