### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by alesoft73** [nonsleepr/ha-eufy-security#2]
Hi, i have intall your component with HACS but when i insert login e password in integration don't login.
Is possible ??
Many thanks!

**Comment by nonsleepr** [comment]
Do you have any relevant info in the logs?

**Comment by alesoft73** [comment]
i have this...

2019-12-10 22:26:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 122, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 48, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 90, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 89, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 132, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/eufy_security/config_flow.py", line 56, in async_step_user
    user_input[CONF_USERNAME], user_input[CONF_PASSWORD], session
  File "/usr/local/lib/python3.7/site-packages/eufy_security/api.py", line 122, in async_login
    await api.async_update_device_info()
  File "/usr/local/lib/python3.7/site-packages/eufy_security/api.py", line 54, in async_update_device_info
    for device_info in devices_resp["data"]:
KeyError: 'data'

**Comment by nonsleepr** [comment]
It looks like there are no cameras linked to the account and the integration isn't handling it properly. Have you tried to use the same credentials to login from the phone and see if you see the cameras there?

**Comment by alesoft73** [comment]
Yes, i use 2 account.
I have created a second  account for login in integration.
But don't connect.
Don't work any account

**Comment by alesoft73** [comment]
![IMAGE 2019-12-10 22:33:32](https://user-images.githubusercontent.com/46445679/70570911-18510600-1b9d-11ea-80ee-b46221b276a0.jpg)
IN the app i see 2 cam

**Comment by nonsleepr** [comment]
I will try to fix the "Unexpected error" in [`python-eufy-security`](https://github.com/FuzzyMistborn/python-eufy-security) to at least properly handle the issue.

What country are you from? Right now the package uses hardcoded endpoint, which, I think, is for the US. Might be that's the reason why the cameras are not seen.

**Comment by alesoft73** [comment]
I leave in taly .... ;)

**Comment by nonsleepr** [comment]
Do you have Pi-Hole installed? If so, can you check what host your phone tries to connect to? (Simply search for "eufy").

**Comment by alesoft73** [comment]
yes...

ipcheck.eufylife.com

**Comment by alesoft73** [comment]
![Schermata 2019-12-10 alle 23 41 27](https://user-images.githubusercontent.com/46445679/70575376-ae3d5e80-1ba6-11ea-99c8-b2f3d8d0b734.png)
This is internet connection

**Comment by nonsleepr** [comment]
Confirmed that the cameras wouldn't be shown when regional endpoints are used. That's fixable. If you're able to manually install `python-eufy-security` into your HA instance, you can try replacing `mysecurity.eufylife.com` in `eufy_security/api.py` to `security-app-eu.eufylife.com`.

Long term fix is coming.

**Comment by alesoft73** [comment]
the modify is in specifc file?

**Comment by alesoft73** [comment]
Ok i attend the fix.
Many thanks!!!!

**Comment by nonsleepr** [comment]
Please confirm that helped.

**Comment by alesoft73** [comment]
confirmed ;)

**Comment by MaxCere** [comment]
same happen to me from italy. I don't understand where I can find api.py....

**Comment by alesoft73** [comment]
> 
> 
> same happen to me from italy. I don't understand where I can find api.py....

If you wont to access the file, connect with port 2222 with Hassio.
https://developers.home-assistant.io/docs/en/hassio_debugging.html

**Comment by bachya** [comment]
@alesoft73 @MaxCere We just released version 0.3.0 of `python-eufy-security` that should address international addresses dynamically; could you help us test?

**Comment by MaxCere** [comment]
It works. No more error and I can se my camera and the entry sensor. Thanks!

**Comment by alesoft73** [comment]
Confirmed, now work.
For donation?

**Comment by alesoft73** [comment]
Login ok... I have 2 cam.
when i press the cam don't show the streaming.
why?

**Comment by nonsleepr** [comment]
For now you have to manually fire an event `camera.turn_on` in Dev Tools -> Services.

**Comment by alesoft73** [comment]
Ahh ok for start streaming and stop?

**Comment by nonsleepr** [comment]
I think this was discussed in HA thread. IIRC it would stop the steam itself in 3 minutes.

**Comment by alesoft73** [comment]
Default streaming 3 minutes ??  Ok , i have created a script to start and stop after 5 minutes...
is the same.
Many thanks another.
Work perfect!

**Comment by alesoft73** [comment]
If you wont i have a warnig about component....
This :

2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1225", value "9"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1146", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1240", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1013", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1011", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1239", value "11"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99904", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1015", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1141", value "-58"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1243", value "2"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1229", value "100"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1142", value "-41"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1145", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1101", value "99"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1273", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99901", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1230", value "100"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1246", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1204", value "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1138", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "2111", value "2"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1241", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1131", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1045", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1210", value "180"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1225", value "9"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1146", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1240", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1011", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1013", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99904", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1239", value "13"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1015", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1141", value "-72"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1243", value "2"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1229", value "100"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1142", value "-62"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1145", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1101", value "99"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1273", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1230", value "100"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99901", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1246", value "0"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1204", value "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=="
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1138", value "5"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "2111", value "2"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1131", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1045", value "1"
2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1210", value "122"

**Comment by nonsleepr** [comment]
What kind of cameras/bases do you have?

**Comment by alesoft73** [comment]
This
![EUFYCAM](https://user-images.githubusercontent.com/46445679/70911427-2f1ab100-2012-11ea-8337-0017eb9c789e.jpg)

**Comment by MaxCere** [comment]
> If you wont i have a warnig about component....
> This :
> 
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1225", value "9"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1146", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1240", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1013", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1011", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1239", value "11"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99904", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1015", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1141", value "-58"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1243", value "2"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1229", value "100"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1142", value "-41"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1145", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1101", value "99"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1273", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99901", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1230", value "100"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1246", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1204", value "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1138", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "2111", value "2"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1241", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1131", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1045", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1210", value "180"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1225", value "9"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1146", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1240", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1011", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1013", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99904", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1239", value "13"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1015", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1141", value "-72"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1243", value "2"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1229", value "100"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1142", value "-62"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1145", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1101", value "99"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1273", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1230", value "100"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99901", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1246", value "0"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1204", value "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=="
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1138", value "5"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "2111", value "2"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1131", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1045", value "1"
> 2019-12-16 01:07:52 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1210", value "122"

Same warinng to me.

**Comment by MaxCere** [comment]
> What kind of cameras/bases do you have?

I have:
HomeBase (v1)
Camera (v1)
2x door sensor.

Purchased from kickstarter. They are the first released version of HW by Eufy.
