### ISSUE TITLE
No entities

### ISSUE THREAD

**Issue by skank01** [nonsleepr/ha-eufy-security#29]
I get no entitites in the integration tab of HA

Log gives:
Logger: homeassistant.components.camera
Source: custom_components/eufy_security/camera.py:46
Integration: Camera (documentation, issues)
First occurred: 19:56:17 (1 occurrences)
Last logged: 19:56:17

Error while setting up eufy_security platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

**Comment by skank01** [comment]
Found a fix
The fix is to edit config/custom_components/eufy_security/camera.py, replacing lines 46 & 47 with

Copy to clipboard
        self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary)
        self._ffmpeg_stream = CameraMjpeg(self._ffmpeg.binary)

There was smth about the loop next to it.


I now get 2 entities, a camera for doorbell and camera for eufycam 2

**Comment by timdonovanuk** [comment]
Nice, this fix worked, thanks @skank01. Any chance of creating a pull request?

**Comment by Tscherno** [comment]
Is that already merged? It doesn't work for me yet.

**Comment by cureheaded** [comment]
thank you, that fixed it for me, been struggling with this for weeks. I can now finally use apk and home-assistant together

**Comment by ayanes21** [comment]
I followed the steps and the camera shows up as single entity not two like others say.  I also can't use the motion sensor as a trigger for automations.  any thoughts?  I am also getting the following errors showing in the logs.
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1163", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1010", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1702", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1240", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1717", value "17"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1243", value "2"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1148", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1716", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1294", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1210", value "112"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1708", value "80"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "99904", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1239", value "9"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1710", value "{"notification_motion_onoff":1,"notification_ring_onoff":1,"notification_style":3}"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1241", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1204", value "eyJwb2ludHMiOltdLCJhY2NvdW50IjoiNGEzYjUwNDJmN2EwODlmNDBiNTgxOTRiNDFkNTM1MzI0NTM5MDE5OSJ9"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1142", value "-42"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1145", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1705", value "5"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1703", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1246", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1013", value "1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1276", value "3"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1015", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1181", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1225", value "9"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1149", value "-1"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1714", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1101", value "98"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1230", value "100"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1229", value "100"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1045", value "0"
2021-07-01 16:41:33 WARNING (MainThread) [eufy_security.camera] Unable to process parameter "1718", value "0"

**Comment by umutcelebi** [comment]
I followed this to change the camera.py and got now 2 entities of the camera's but i have no live footage. 1 camera has nothing and 1 camera just shows a picture from 4 months ago. Any updates?
