### ISSUE TITLE
Error after login: custom_components/eufy_security/camera.py:46

### ISSUE THREAD

**Issue by Na3blis** [nonsleepr/ha-eufy-security#34]
I added the repository, logged into eufy and recurved the following error:

Log Details (ERROR)
Logger: homeassistant.components.camera
Source: custom_components/eufy_security/camera.py:46
Integration: Camera (documentation, issues)
First occurred: 9:49:27 PM (1 occurrences)
Last logged: 9:49:27 PM

Error while setting up eufy_security platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

This is on the latest HA Container

**Comment by realmadridsi** [comment]
I had the same issue. This fixed it for me:

https://community.home-assistant.io/t/eufy-camera-integration/121758/383

**Comment by l3nticular** [comment]
This was apparently fixed in master 2 months ago, but a new tag was never generated.  Use "master" when installing with HACS and it works.

**Comment by unarj** [comment]
I didn't see "master" in HACS but I did see "main" which did not have this fix.  thanks!
