### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by hamdanfadi** [nonsleepr/ha-eufy-security#37]
Hi there,
After adding configuration > Integration I was prompting with username and password. I have used my eufy account, but keep asking for it! What I should do?

**Comment by mmz06** [comment]
Hi There,

Same issue for me. Any help ?
Here are the logs:
`[33m2021-03-15 09:54:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m`
`[33m2021-03-15 09:54:18 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'eufy_security'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'eufy_security'[0m`

**Comment by hamdanfadi** [comment]
Yes just make another user in Eufy it should work

**Comment by waudoglio** [comment]
> Yes just make another user in Eufy it should work

Hi, same issue, same workaround. I'don't understand why an account is working and another one no. 
BTW, which device do you have connected to the home base? I have a doorbell but HA is not finding any entity inside this Eufy Security integration

**Comment by hamdanfadi** [comment]
Do you have MFA enabled in eufy?


On 18/03/2021, at 05:36, waudoglio ***@***.***> wrote:

﻿

Yes just make another user in Eufy it should work

Hi, same issue, same workaround. I'don't understand why an account is working and another one no.
BTW, which device do you have connected to the home base? I have a doorbell but HA is not finding any entity inside this Eufy Security integration

**Comment by mmz06** [comment]
> Do you have MFA enabled in eufy? 

Yes, MFA is enabled for my account

**Comment by hamdanfadi** [comment]
Integration doesn't support MFA. So you have to disable it for HA' user and don't make it admin just guest account.

**Comment by waudoglio** [comment]
Sorry guys, I don't get what MFA is.. Can you explain what you mean with MFA? I removed the sharing of the doorbell for the 2nd user (the one inserted in HS) and replaced it with a guest one... But still no entity appears in eufy security integration.
Thanks for the support

**Comment by hamdanfadi** [comment]
Multi factor authentication

**Comment by waudoglio** [comment]
So no, I've no MFA on secondary account, just on the primary one

**Comment by hamdanfadi** [comment]
Do you have Anydesk installed in your computer? I will jump into your computer and I will do it for you

**Comment by waudoglio** [comment]
Ehm... no... At the moment I have Hassio on Rpi4 (nothing like Anydesk on this) and Eufy Home security on a couple of android devices... 

Sorry I'm vey noobie on this world, just installed hassio one week ago... :( I appreciate very much your prompt support

> Do you have Anydesk installed in your computer? I will jump into your computer and I will do it for you From: waudoglio ***@***.***> Sent: Thursday, 18 March 2021 10:01 PM To: nonsleepr/ha-eufy-security ***@***.***> Cc: Fadi Hamdan ***@***.***>; Author ***@***.***> Subject: Re: [nonsleepr/ha-eufy-security] Login failed (#37) So no, I've no MFA on secondary account, just on the primary one - You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnonsleepr%2Fha-eufy-security%2Fissues%2F37%23issuecomment-801751178&data=04%7C01%7C%7C483ac03982f5438f264a08d8e9ec55c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637516548574960249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U74zk8CCt51ZfXJ8y2EqcfR%2FV7tTgVtFeMCKkLqNO9A%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALINWFZRZ2TKSY67XDS4B6LTEG6MJANCNFSM4ZDYWM7A&data=04%7C01%7C%7C483ac03982f5438f264a08d8e9ec55c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637516548574960249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lJePjeXf31%2BpXaFepzEobKInn5C3Yuoq5EGuUqErezw%3D&reserved=0>.

**Comment by waudoglio** [comment]
Moreover at the moment I'm at work, on this PC the network does not allow me to access my Rpi by remote using dynDNS provider. So unfortunately the direct support connection is impossible :(

**Comment by mmz06** [comment]
@hamdanfadi: It works well now with this secondary guest non MFA enabled user...
Thank you !
:-)
Any Plans for MFA support ?

**Comment by hamdanfadi** [comment]
I’m a user like you. You can ask the developer

On 18/03/2021, at 23:01, mmz06 ***@***.***> wrote:

﻿

@hamdanfadi<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhamdanfadi&data=04%7C01%7C%7C46822d1e2e844fcd4bba08d8e9f4c9de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637516584864378544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mefhIctl9yiENrdddw6k4%2BJiWzYpjn4EmfzLGifeNL0%3D&reserved=0>: It works well now with this secondary guest non MFA enabled user...
Thank you !
:-)
Any Plans for MFA support ?

**Comment by mmz06** [comment]
> I’m a user like you. You can ask the developer

I missed that... Sure !

**Comment by waudoglio** [comment]
Maybe this can help to understand the issue. System log reports this error at startup:

Error while setting up eufy_security platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
 
Which device do you have connected to home security? Can it be related to the doorbell device? Or am I missing something?

**Comment by gregoryduckworth** [comment]
> Which device do you have connected to home security? Can it be related to the doorbell device? Or am I missing something?

I have the exact same error log and it relates to a doorbell.
