### ISSUE TITLE
Camera don't appear

### ISSUE THREAD

**Issue by parano78** [nonsleepr/ha-eufy-security#44]
Hello,

i have followed every installation step carefully, but i can't seem to see the camera in the devices list or in the dashboard :(

anyone had this problem ?

(yes i restarted HA after installation)

**Comment by rogersmj** [comment]
Same issue. Got the integration installed and configured with my Eufy credentials, but there are no devices/entities associated to it.

**Comment by DivanX10** [comment]
**A similar problem. It costs Home Assistant 2021.5.0, Eufy Indoor Cam 2K Pan and Tilt. Created a second account, turned off two-factor authorization, and granted the second account full access to the camera on the first account. The camera did not appear in the integration.**

Аналогичная проблема. Стоит Home Assistant 2021.5.0, камера Eufy Indoor Cam 2K Pan и Tilt. Создал вторую учетную запись, выключил двухфакторную авторизацию, предоставил полный доступ второй учетной записи к камере на первой учетной записи. Камера не появилась в интеграции.


```
Logger: homeassistant.components.camera
Source: custom_components/eufy_security/camera.py:46
Integration: Камера (documentation, issues)
First occurred: 2:04:19 (3 occurrences)
Last logged: 2:12:30

Error while setting up eufy_security platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
```

**Comment by saiajin** [comment]
Newbie here... same issues.... installed HACS was able to add the integration but I get no camera devices or entities and then I'm lost from there... any direction would be appreciated

**Comment by DivanX10** [comment]
**I added the camera to the Home Assistant, but in a different way, read** [**here**](https://community.home-assistant.io/t/eufy-camera-integration/121758/1208?u=divanx10)

Я добавил камеру в Home Assistant, но другим способом, читать [здесь](https://community.home-assistant.io/t/eufy-camera-integration/121758/1208?u=divanx10)

**Comment by geidorei** [comment]
Ditto - not finding the doorbell? Any suggestions appreciated.

**Comment by sbrighty** [comment]
Worked it out. I needed to login as the new account in the App and accept the sharing request. Once that was done restarting HA resolved this same issue for me. Good luck all.

**Comment by DivanX10** [comment]
`Worked it out. I needed to login as the new account in the App and accept the sharing request. Once that was done restarting HA resolved this same issue for me. Good luck all.`

**What kind of camera do you have? About the account. This is what it is written that you need to use a second account, where the main account is given access to the second account and then the camera will fly, but not everyone works. Perhaps your camera is supported by this integration, and my Eufy Indoor Cam 2K Pan & Tilt camera did not take off in this integration.**

Какая у вас камера? Про учетную запись. Об этом и пишется, что нужно использовать вторую учетную запись, где на основной учетной записи дается доступ второй учетной записи и тогда камера залетит, но не у всех это работает. Возможно ваша камера поддерживается данной интеграции, а моя камера Eufy Indoor Cam 2K Pan & Tilt не взлетела в этой интеграции.

**Comment by sbrighty** [comment]
@DivanX10 homebase2 with doorbell. I had the same issue as described here. The fix for me was to use the IOS app and login with the second account, go through the region selection and then after a few moments the sharing request was received, which I approved. Then restarted HA and the entity appeared. Give it a try in your iOS or Android app with your secondary account. Using your secondary account can you see your homebase?

**Comment by geidorei** [comment]
Tried that, but didn't work.... Hummmmmm. lol

**Comment by geidorei** [comment]
found the fix, well it works on mine: https://community.home-assistant.io/t/eufy-camera-integration/121758/383

**Comment by DivanX10** [comment]
Спасибо, у меня после  исправления появилась камера, но нет ничего, кроме одного объекта. Камера в этой интеграции ужасна. Я использую камеру через Motion Eye


![image](https://user-images.githubusercontent.com/64090632/118371425-4b2ed300-b5b5-11eb-9fb4-7e15d2498d47.png)

**Comment by DivanX10** [comment]
Thank you, it helped. The camera appeared. But unfortunately this is not the case. I thought that there would be sensors and controls in addition to the camera, but there is nothing. For me, it is better to use the eufy-security integration in iobroker, and from there already throw it to HA. Which I did, and I'm very happy with it.  The author yesterday [corrected](https://github.com/bropat/ioBroker.eufy-security/issues/130) sensors and they worked for me. 

This is what the card looks like in the integration
![image](https://user-images.githubusercontent.com/64090632/118371523-a82a8900-b5b5-11eb-8fea-6bf2fcec7614.png)

About the camera. I thought the camera would show a video stream, and shows a snapshot of the last event. Not an option. I did it through Motion eye. Below is a link to the comparison [video](https://drive.google.com/file/d/1I7mQ7NN-dcEahczDQ2dzmeO6mhxFOTOf/view?usp=sharing) between webrtc and motion eye

All these controls work
![image](https://user-images.githubusercontent.com/64090632/118371785-d6f52f00-b5b6-11eb-9e2a-d04457333436.png)


-------------------

Спасибо вам, это помогло. Камера появилась. Но к сожалению это не то. Я думал, что там кроме камеры будут и сенсоры и управление, но ничего нет. По мне лучше использовать интеграцию eufy-security в iobroker, а от туда уже перекидывать в ХА. Что я и сделал и очень доволен.  Автор вчера [исправил](https://github.com/bropat/ioBroker.eufy-security/issues/130) сенсоры и они у меня заработали. 

Вот так выглядит карточка в интеграции
![image](https://user-images.githubusercontent.com/64090632/118371523-a82a8900-b5b5-11eb-8fea-6bf2fcec7614.png)

Про камеру. Я думал, что камера будет показывать видеопоток, а показывает снимок последнего события. Не вариант. Я сделал через Motion eye. Ниже ссылочка на сравнение [видео](https://drive.google.com/file/d/1I7mQ7NN-dcEahczDQ2dzmeO6mhxFOTOf/view?usp=sharing) между webrtc и motion eye

Все эти управления работают
![image](https://user-images.githubusercontent.com/64090632/118371785-d6f52f00-b5b6-11eb-9e2a-d04457333436.png)

**Comment by geidorei** [comment]
I had a look a iobroker, and will have a look in future, but iobroker looks a bit of a nightmare! Lol
