### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by liudger** [nonsleepr/ha-eufy-security#45]
2021-05-02 17:09:35 ERROR (MainThread) [homeassistant.components.camera] Error while setting up eufy_security platform for camera
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
[EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
[EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

**Comment by nwalk7800** [comment]
You probably need to update to a version after change 530d9b6355c189d9979958fde23572be5e89a52f

**Comment by liudger** [comment]
That is weird I should have the latest. I'll do a manual pull. Thanks for the link with the fix!
