### ISSUE TITLE
Loop error in init

### ISSUE THREAD

**Issue by Spiffo** [nonsleepr/ha-eufy-security#58]
Just installed the package through HACS (modifying the manifest to contain the version, like discussed elsewhere on this repo), and got following error:

> 2021-07-02 10:38:43 ERROR (MainThread) [homeassistant.components.camera] Error while setting up eufy_security platform for camera
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
> await asyncio.shield(task)
> File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
> [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
> File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
> [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
> File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
> self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
> TypeError: __init__() got an unexpected keyword argument 'loop'

Anyone got any idea?

**Comment by Spiffo** [comment]
And a while later:

> Traceback (most recent call last):
> File "/config/custom_components/eufy_security/__init__.py", line 87, in refresh
> await api.async_update_device_info()
> File "/usr/local/lib/python3.8/site-packages/eufy_security/api.py", line 57, in async_update_device_info
> devices_resp = await self.request("post", "app/get_devs_list")
> File "/usr/local/lib/python3.8/site-packages/eufy_security/api.py", line 114, in request
> raise RequestError(
> eufy_security.errors.RequestError: There was an unknown error while requesting app/get_devs_list: 503, message='Service Temporarily Unavailable', url=URL('https://security-app-eu.eufylife.com/v1/app/get_devs_list')

**Comment by profucius** [comment]
Just figured this out. I deleted the files in the custom_components/eufy_security folder, and transferred the files downloaded straight from the github repo. Edited the manifest.json for version. Uploaded and then reboot the Supervisor, not only the regular reboot. Now I can access camera fine.
