### ISSUE TITLE
custom_components/eufy_security/camera.py:46 

### ISSUE THREAD

**Issue by sanderbohm** [nonsleepr/ha-eufy-security#68]
After the integration is installed i get the follow error in my logs:

Error while setting up eufy_security platform for camera

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

**Comment by jamie-dit** [comment]
Getting the same issue as well. I had to edit the manifest version after install from HACS to setup the integration
