### ISSUE TITLE
Update 2022.3.0

### ISSUE THREAD

**Issue by alesoft73** [nonsleepr/ha-eufy-security#74]
Dear @nonsleepr , sorry if i diturb.
Are you planning to update the code for home assistant 2022.3 ??
Thanks for any reply.
And thanks for your work.

**Comment by alesoft73** [comment]
This is an error..
Unable to install package python-eufy-security==0.3.0: ERROR: Cannot install python-eufy-security==0.3.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by prnewman** [comment]
I received these errors after upgrading to Home Assistant 2022.3.1:

![image](https://user-images.githubusercontent.com/857199/156928156-b66df1f8-c823-49a8-86e5-84c13931ec58.png)

![image](https://user-images.githubusercontent.com/857199/156928017-c2bf774b-57ea-4452-a3c8-fffb3ee70ffa.png)

**Comment by toddsay** [comment]
I had the same issue on 2022.3.1, and was able to get this working with a local change. In my HA config directory I located file `custom_components/eufy_security/manifest.json` (I'm using HACS) and removed the version requirement for the dependency `python-eufy-security`.

```
  "requirements": [
    "python-eufy-security"
  ],
```
After another HA restart this allowed me to complete the setup and it seems to be generally working (sometimes my eufy doorbell image doesn't seem to load on my dashboard, but I had that problem previously too). Presumably this means I am using the latest version of the python-eufy-security package, and I don't know whether that implies any other change that should be made to this one. But it doesn't appear that this repo has been touched lately so I'm not sure if we will be getting a formal fix.

**Comment by sfgrabowski** [comment]
I tried the above fix, but I am now unable to add the integration after removing it. I installed again via HACS, made the change above, but it doesn't appear. I'm not sure which step I'm missing.

**Comment by toddsay** [comment]
So you [re]installed via HACS, restarted HA, and can't find it in HA's integrations list? I had this problem too, and some research told me that browser caching is involved. In my case, a simple ctrl+f5 solved it.

**Comment by nerajchand** [comment]
I've got a similar issue to @sfgrabowski 
I used to have this integration working until the 2022.3.0 update. 
I then tried the fix that @toddsay mentioned which didn't work. 
Then also tried to remove & re-add. This has re-added in via HACS, but i'm unable to find the intergration to actually complete the setup. 

Tried clearing cache & using a different device, but still can't see the eufy_security integration anymore.
Also rebooted HA after the removal + install process.

**Comment by alesoft73** [comment]
@sfgrabowski @toddsay @nerajchand 
Please try this change if it works ..:



{
  "domain": "eufy_security",
  "name": "Eufy Security",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/eufy_security",
  "version": "1.0",
  "requirements": [
  "python-eufy-security"
  ],
  "dependencies": [
  "ffmpeg"
  ],
  "codeowners": [
  "@nonsleepr"
  ]
  }

**Comment by alesoft73** [comment]
> I had the same issue on 2022.3.1, and was able to get this working with a local change. In my HA config directory I located file `custom_components/eufy_security/manifest.json` (I'm using HACS) and removed the version requirement for the dependency `python-eufy-security`.
> 
> ```
>   "requirements": [
>     "python-eufy-security"
>   ],
> ```
> 
> After another HA restart this allowed me to complete the setup and it seems to be generally working (sometimes my eufy doorbell image doesn't seem to load on my dashboard, but I had that problem previously too). Presumably this means I am using the latest version of the python-eufy-security package, and I don't know whether that implies any other change that should be made to this one. But it doesn't appear that this repo has been touched lately so I'm not sure if we will be getting a formal fix.

Now we can't login ;) 

![immagine](https://user-images.githubusercontent.com/46445679/156987736-d0f176f7-9713-4313-b2e4-40e31f7e4f48.png)

:-(

**Comment by toddsay** [comment]
There was one other thing I did prior to removing the version requirement for `python-eufy-security`. Sorry, I should have mentioned this, as it may be important:

When downloading the eufy integration via HACS, it was defaulting to the latest released version, 0.30. But there were actually a few changes made here after that version, just not given a formal release. So I changed the version dropdown to "master" when installing, then removed the version requirement from the manifest and restarted HA.

@alesoft73, I'm not sure what is going wrong there but that looks bad. :( Hopefully your logs will give more insight into what is happening.

**Comment by nerajchand** [comment]
Unfortunately that hasn't resolved the issue for me. 
The issue that we're facing now where we can't find "Eufy Security" in integrations seem to be tracked in #72 


> There was one other thing I did prior to removing the version requirement for `python-eufy-security`. Sorry, I should have mentioned this, as it may be important:
> 
> When downloading the eufy integration via HACS, it was defaulting to the latest released version, 0.30. But there were actually a few changes made here after that version, just not given a formal release. So I changed the version dropdown to "master" when installing, then removed the version requirement from the manifest and restarted HA.
> 
> @alesoft73, I'm not sure what is going wrong there but that looks bad. :( Hopefully your logs will give more insight into what is happening.

**Comment by alesoft73** [comment]
I think the problem is python-eufy-security ,
in the update version the login and password is changed... ;)

Hopefully someone or @nonsleepr will be able to solve it.
This integration was perfect and working.
It's a shame.
Maybe if some donation could move the creator;)

**Comment by toddsay** [comment]
That other issue thread @nerajchand referenced also mentions a login issue related to 2FA settings on the eufy account. Is that the error you are hitting @alesoft73? That user mentioned turning off 2FA to get around it so maybe that would help you. It seems likely that the integration doesn't speak 2FA.

**Comment by alesoft73** [comment]
I don't use 2fa ;)...

This is a error:



Logger: aiohttp.server
Source: custom_components/eufy_security/config_flow.py:55
Integration: Eufy Security
First occurred: 08:32:39 (4 occurrences)
Last logged: 08:35:23
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 166, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eufy_security/config_flow.py", line 55, in async_step_user
    await async_login(
  File "/usr/local/lib/python3.9/site-packages/eufy_security/api.py", line 122, in async_login
    await api.async_update_device_info()
  File "/usr/local/lib/python3.9/site-packages/eufy_security/api.py", line 54, in async_update_device_info
    for device_info in devices_resp["data"]:
TypeError: 'NoneType' object is not iterable

**Comment by prnewman** [comment]
> There was one other thing I did prior to removing the version requirement for `python-eufy-security`. Sorry, I should have mentioned this, as it may be important:
> 
> When downloading the eufy integration via HACS, it was defaulting to the latest released version, 0.30. But there were actually a few changes made here after that version, just not given a formal release. So I changed the version dropdown to "master" when installing, then removed the version requirement from the manifest and restarted HA.

This worked for me. I just checked out `master` and replaced `eufy_security` folder on HA (after editing `manifest.json`).

**Comment by toddsay** [comment]
I'm not sure how that dependency `python-eufy-security` (`eufy_security` folder) is managed, or even which versions are usable with `ha-eufy-security`, but this might suggest that those still encountering errors are running a different version of that project.

**Comment by OlivierHens** [comment]
> I don't use 2fa ;)...
> 
> This is a error:
> 
> Logger: aiohttp.server Source: custom_components/eufy_security/config_flow.py:55 Integration: Eufy Security First occurred: 08:32:39 (4 occurrences) Last logged: 08:35:23 Error handling request
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle result = await result File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 166, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper result = await method(view, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure result = await self._async_handle_step(flow, cur_step["step_id"], user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step result: FlowResult = await getattr(flow, method)(user_input) File "/config/custom_components/eufy_security/config_flow.py", line 55, in async_step_user await async_login( File "/usr/local/lib/python3.9/site-packages/eufy_security/api.py", line 122, in async_login await api.async_update_device_info() File "/usr/local/lib/python3.9/site-packages/eufy_security/api.py", line 54, in async_update_device_info for device_info in devices_resp["data"]: TypeError: 'NoneType' object is not iterable

Have you managed to find a solution? 

Thanks!
