### ISSUE TITLE
Issue: Eufy Doorbeel camera integration with Home Assistant

### ISSUE THREAD

**Issue by danny0803** [nonsleepr/ha-eufy-security#83]
Hello, 

I am having issues integrating Eufy doorbel to Home asistant. I have disable two factor authentication and nothing seems to work. I get the following error. 

 Add-on: ⚰️ Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:55:39] INFO: Exporting log level for nodejs: info
[14:55:39] INFO: Symlinking data dir
[14:55:39] INFO: Running 'eval' commands
[14:55:39] INFO: Generating config.yml from options.json
[14:55:39] INFO: Image build with version 0.2.24
[14:55:39] INFO: starting original stuff...

> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js

error: Error -- httpService.listDevices Response code 403 (Forbidden) {"name":"HTTPError","timings":{"start":1701892540098,"socket":1701892540101,"lookup":1701892540105,"connect":1701892540121,"secureConnect":1701892540148,"upload":1701892540149,"response":1701892540212,"end":1701892540225,"phases":{"wait":3,"dns":4,"tcp":16,"tls":27,"request":1,"firstByte":63,"download":13,"total":127}},"stack":"HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2023-12-06T19:55:40.235Z"}
info: Credentials found -> reusing them... {"timestamp":"2023-12-06T19:55:45.333Z"}
error: Error -- httpService.registerPushToken Response code 403 (Forbidden) {"name":"HTTPError","timings":{"start":1701892545409,"socket":1701892545410,"lookup":1701892545410,"connect":1701892545427,"secureConnect":1701892545440,"upload":1701892545441,"response":1701892545498,"end":1701892545499,"phases":{"wait":1,"dns":0,"tcp":17,"tls":13,"request":1,"firstByte":57,"download":1,"total":90}},"stack":"HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2023-12-06T19:55:45.500Z"}

**Comment by kevin99207** [comment]
got it fixed?
